FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash zelantus

RUN mkdir /etc/zelantus

RUN mkdir /var/lib/zelantus

RUN chown zelantus:zelantus /etc/zelantus /var/lib/zelantus

WORKDIR /home/zelantus

COPY --chown=zelantus:zelantus linux64/* ./run.sh /home/zelantus/

USER zelantus

CMD ["/home/zelantus/run.sh"]
